-- Fachrichtungen - x8102dep
-- Fachrichtungen zeitabhängig - x8117dpt
-- Fachrichtungen/Stationen - x8112des
-- Zentren/Fachrichtungen - x8111cep
-- Abrechnungsarten für Fachrichtung+Station - x8302cpi
-- Abrechnungsart-Fachrichtung-Station-Tarifziffer - x8303pla
-- Erbringende Leistungsstellen mit Untersuchungen - x8805lae
-- Zuordnung Ressourcen zu Leistungsstelle - x8872crn
-- Zuordnung Profil - Fachrichtung/Station - x9142pdw
-- Fachrichtung - Vorlagen Zuordnung - x5811ded
--OP Leistungen x8720srv
--OP Leistungen x8721sra
-- Diagnose-Fachrichtung-Zuordnung - x6008ddr

